# Generated by Django 5.0.6 on 2024-07-06 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("letter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send",
                    models.DateTimeField(verbose_name="дата и время первой отправки"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Раз в день"),
                            ("week", "Раз в неделю"),
                            ("month", "Раз в месяц"),
                        ],
                        max_length=10,
                        verbose_name="период отправки",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="статус отправки")),
                (
                    "client",
                    models.ManyToManyField(
                        to="client.client", verbose_name="получатель"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letter.letter",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
