# Generated by Django 5.0.6 on 2024-07-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("letter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_send",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="дата и время последней отправки",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="статус отправки"),
                ),
                (
                    "mail_server_answer",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ответ SMPT сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send",
                    models.DateTimeField(verbose_name="дата и время первой отправки"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Раз в день"),
                            ("week", "Раз в неделю"),
                            ("month", "Раз в месяц"),
                        ],
                        max_length=10,
                        verbose_name="период отправки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("create", "Создана"),
                            ("active", "В работе"),
                            ("end", "Завершена"),
                        ],
                        default="create",
                        verbose_name="статус отправки",
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="client.client", verbose_name="получатель"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.mailing",
                        verbose_name="попытка рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letter.letter",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
