# Generated by Django 5.0.6 on 2024-07-06 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100, verbose_name="ФИО")),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Электронная почта"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Тема")),
                ("text", models.CharField(max_length=100, verbose_name="Тело")),
            ],
            options={
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send",
                    models.DateTimeField(verbose_name="дата и время первой отправки"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("day", "Раз в день"),
                            ("week", "Раз в неделю"),
                            ("month", "Раз в месяц"),
                        ],
                        max_length=10,
                        verbose_name="период отправки",
                    ),
                ),
                ("status", models.BooleanField(verbose_name="статус отправки")),
                (
                    "client",
                    models.ManyToManyField(
                        to="letter.client", verbose_name="получатель"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letter.letter",
                        verbose_name="сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
