# Generated by Django 5.0.6 on 2024-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Letter",
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="client",
            field=models.ManyToManyField(
                to="newsletter.client", verbose_name="получатель"
            ),
        ),
    ]
