# Generated by Django 5.0.6 on 2024-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("newsletter", "0002_delete_letter_alter_newsletter_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="client",
            field=models.ManyToManyField(to="client.client", verbose_name="получатель"),
        ),
    ]
