# Generated by Django 5.0.6 on 2024-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_remove_newsletter_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[("off", "Отключена"), ("on", "Включена")],
                default="off",
                verbose_name="статус отправки",
            ),
        ),
    ]
