# Generated by Django 5.0.6 on 2024-07-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_alter_newsletter_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="newsletter.newsletter",
                verbose_name="попытка рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("done", "Успех"), ("error", "Ошибка")],
                default="error",
                verbose_name="статус отправки",
            ),
        ),
    ]
