# Generated by Django 5.0.6 on 2024-07-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("done", "Успех"), ("error", "Ошибка")],
                verbose_name="статус отправки",
            ),
        ),
    ]
