# Generated by Django 5.0.6 on 2024-07-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0006_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [("set_status", "Может менять статус рассылки ")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
